### ISSUE TITLE
Double Agent Training

### ISSUE THREAD

**Issue by zhey16** [mhyrzt/Simple-MADRL-Chess#1]
Hi, just a short question (may be I miss some codes). During the training of DoubleAgents, I see the DoubleAgent class overrides th learn method so both whiteNetwork and blackNetwork have been trained. But DoubleAgent does not override the train_episode and take_action methods. It is still using self.learner for sampling, not using black and white agent. And also self.learner neural network has not been updated.

Did I missed some codes or it's supposed to be like this?

I thought we should use blackAgent and whiteAgent to make moves during sampling...

**Comment by mhyrzt** [comment]
Hell There :D

first, sorry for my silly grammatical mistakes!

1. There is no need to override the base class since it will act and store based on whose turn it is, and it will store them in an episodic buffer, respectively.

2. `train_episode` does not necessarily train an episode; it will just play it. (Maybe I named it poorly; sorry for that. 😢)

3. If you take a look at the `train` method, you will see that it will train after `n` episodes.

**Comment by zhey16** [comment]
Sorry in advance if I misunderstand any concept, I am just a new beginner of reinforcement learning, just trying to figure something out.

I can see that in DoubleAgents training, the `whiteAgent` and `blackAgent` have been trained after n episodes. But in `train_episodes`, I think it's still the `self.learner` playing against itself. I am just quiet confused on this part, because I thought `whiteAgent` and `black Agent` should play against each other in the `train_episode` function.

**Comment by mhyrzt** [comment]
OMG!
now i checked it and you are absolutely right!
